# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: 'fn-devops-sp1'
  EnvironmentType: 'Test'
  ResourceGroupName: 'rg-bicep-demo'
  DeploymentDefaultLocation: 'qatarcentral'

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      location: $(DeploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: lab-6/main.bicep
      overrideParameters: >
        -environmentType $(EnvironmentType)